### ISSUE TITLE
Missing author on GRAIL - A Music Identity Space API

### ISSUE THREAD

**Issue by MDBarone** [ismir-net/ismir2016-lbd#51]
Hi Colin and Eric,
My supervisor, Matthew Woolhouse, does not seem to appear in the list of publications for the GRAIL paper. Would it be possible to update this information? It would be useful in order to receive reimbursement for the conference from university accounts. 

Thanks,
Michael

**Comment by craffel** [comment]
Oops, missed the second line of authors!  Updated.

**Comment by MDBarone** [comment]
Thanks Colin, will this update on the ISMIR 2017 page as well?

**Comment by craffel** [comment]
Yep, give it a bit...

**Comment by craffel** [comment]
Updated!
